API_ID: 26807366
API_HASH: 66932558c5b01c9284573b58a720d10d
BOT_TOKEN: 6229097524:AAHyRxOyZSYHR1ti33YXgPkTI22uNtyO3TU

MONGO_URL: mongodb+srv://anasphtml:ASShaw96@lucifercc.98bc6d0.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-18236.c13.us-east-1-3.ec2.cloud.redislabs.com
REDIS_PORT: 18236
REDIS_PASS: X5X9q4Wh3LZhw4IjJNjAxOzKEVIO0QOi

SESSION_API_ID: 26807366
SESSION_API_HASH: 66932558c5b01c9284573b58a720d10d
SESSION_STRING: 1BVtsOJMBuxRbEPmNbx6oWeUBAycsJZfdxyixHkE5uTn-BGijsVJc2GTs49AkYmUkByMKMQ4g_Ub-VFddTb4BtsbNddeeLDP9H1QRpt_5odU0G_S_T26gSMPy6nS6pqm75UslWcYS3JO-QR2A_C8_TkN4QeMjAjEOxNYnUE72msabnIBYuULQgrbzjU4WnuicGMyGU35Q5wytjKnBIJhR0do-28ZbOxHVaeQkj5n0kysqbeDcVL4I4tQuascsuwKqsKDHCQO_W4iYBNBHX4PLgrFI_dLNTQwMTNzV_Gma-Ir7_6WMvTsghspB0ebRwJg0ZaVRnpBoHxmOIPo6GBTxY3BJtkc77CE=

ADMINS: 
  - 6080652741
  - 5871846598

OWNER: 5871846598

BOT_PIC: https://telegra.ph/file/8dbd4a5b3f39f41b9a484.jpg
OWNER_PIC: https://telegra.ph/file/ea0382ffdfa7a7c2d2539.jpg


SUPPORT_CHAT: IXI_V1 
# LOG_CHAT: 
LOG_CHAT: -1001938845044



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

